### ISSUE TITLE
Data loss handling

### ISSUE THREAD

**Issue by antonsking** [gopher-motorsports/trackside-telemetry#3]
Since the program expects all the data all the time, data is lost if the packet is not complete, resulting in ValueErrors or IndexErrors. They are handled, but the data is lost. Consider implementing broader fixes to this problem so no data is lost while the car is driving. For the most part, once everything is synced up, it runs smoothly, so confirm that this will always happen.

**Comment by caljay98** [comment]
Checksum will solve this issue
